version: "3.2"
services:
  benford-backend:
    restart: always
    container_name: benford-backend
    # volumes: 
    #   - '.:/benford-backend'
    command : bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./benford-backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  benford-frontend:
    restart: always
    command : npm start
    container_name: benford-frontend
    # volumes: 
    #   - '.:/benford-frontend'
    build:
      context: ./benford-frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - benford-backend
